# Generated by Django 4.1.7 on 2023-03-31 06:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ady')),
                ('author', models.CharField(max_length=100, verbose_name='awtory')),
                ('image', models.ImageField(upload_to='article_img/', verbose_name='suraty')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Beýany')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Goşulan senesi')),
            ],
            options={
                'verbose_name_plural': 'Makalalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
