# Generated by Django 4.1.7 on 2023-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_article_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='awtory'),
        ),
    ]
